services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: cstimer-redis
    ports:
      - '6379:6379'

  server:
    env_file: ".env"
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: cstimer-server
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'

  client:
    env_file: ".env"
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: cstimer-client
    depends_on:
      - server
    ports:
      - '3000:3000'
