services:
  db:
    image: postgres
    env_file: "./server/.env.production"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cstimer
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis
    container_name: cstimer-redis
    ports:
      - '6379:6379'

  server:
    env_file: "./server/.env.production"
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cstimer-server
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'

  client:
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=http://localhost:5000
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_ENDPOINT: http://localhost:5000
    container_name: cstimer-client
    depends_on:
      - server
    ports:
      - '3000:3000'
