services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: cstimer-redis

  server:
    env_file: ".env"
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cstimer-server
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'
